### ISSUE TITLE
Move to noncash.space

### ISSUE THREAD

**Issue by equivalentideas** [frontyardprojects/a-non-cash-assets-library#8]
* [x] make is work without the 'www.'
* [x] change all references in app and in mail system: "I just tried to sign up as a new user and got a *fail* 'cos it still talks to the old DNS"

**Comment by e-e-e** [comment]
OK ok. I will get to this tonight. 👍 its all config options.

**Comment by e-e-e** [comment]
So www is done. But the mailgun settings need to be setup on mailgun for them to take effect. Can I leave this in your hands @equivalentideas . You need to setup the mx records on the new domain as well.

I have changed configs for mailgun to refer to noncash.space. But let me know if you need me to upload new secrets etc.

**Comment by equivalentideas** [comment]
🙏 Thanks @e-e-e 💕

**Comment by equivalentideas** [comment]
## Swap references to whatchamacallit.space to noncash.space:

* [x] change references in the app:
  * [x] in Readme.md

## Reconfigure mailgun

* [x] add new domain
* [x] add mx records in namecheap
* [x] verify dns records have propagated  
* [x] update details in config.json on production server (Ben had already done this)

**Comment by equivalentideas** [comment]
I've set up those records, but now need to wait for DNS records to propagate.

I've pinged @e-e-e to give me access to the production server so I can deploy etc. .

**Comment by equivalentideas** [comment]
This is now complete @cooperstring @e-e-e :) I've verified it's working by signing up for a new account and receiving an email.
